### ISSUE TITLE
Simplify the catalog PR procedure

### ISSUE THREAD

**Issue by jbusecke** [leap-stc/data-management#65]
>              Hmm just like in #63 the validate step seems to get stuck here. 

In general I think the double PR structure is quite cumbersome. @andersy005 instead of making a separate PR, would it be possible to add the relevant code to the PR itself? Or maybe we should just push to main with a helpful commit message (including the PR number?)?

_Originally posted by @jbusecke in https://github.com/leap-stc/data-management/issues/63#issuecomment-1768712676_

**Comment by andersy005** [comment]
i can confirm that this is now working as expected. see: https://github.com/leap-stc/data-management/pull/74

**Comment by andersy005** [comment]
the current setup does not work for pull requests opened from a fork (e.g. https://github.com/leap-stc/data-management/pull/50) due to the limited permissions of the default token/deploy key. I'm happy to look into ways to bypass this permission issue if we want to support all kinds of pull requests extensively.
